"""crear_tabla_espacial_y_sp

Revision ID: 75f63908d172
Revises: 
Create Date: 2026-06-04 22:43:09.349857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import advanced_alchemy.types.guid
import geoalchemy2.types
from app.core.db_scripts import DDL_CREAR_SP_DISTANCE, DDL_BORRAR_SP_DISTANCE

# revision identifiers, used by Alembic.
revision: str = '75f63908d172'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.execute('CREATE EXTENSION IF NOT EXISTS postgis;')
    op.execute(DDL_CREAR_SP_DISTANCE)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pets_locations',
    sa.Column('id', advanced_alchemy.types.guid.GUID(length=16), nullable=False),
    sa.Column('pet_id', sa.Uuid(), nullable=False),
    sa.Column('coordinate', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pets_locations'))
    )
    op.create_index(op.f('ix_pets_locations_pet_id'), 'pets_locations', ['pet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""

    op.execute(DDL_BORRAR_SP_DISTANCE)
    op.execute('DROP EXTENSION IF EXISTS postgis;')

    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_index(op.f('ix_pets_locations_pet_id'), table_name='pets_locations')
    op.drop_table('pets_locations')
    # ### end Alembic commands ###
